services:
  app:
    image: riseupgroup/timetracker
    environment:
      #PRIVATE_KEY: private.pem
      #AUTH_SERVER_KEY: auth_server.pem
      AUTH_SERVER_HOST: auth.riseupgroup.net
      AUTH_SERVER_ID: 0 # replace with your auth server id (service-id)
      DATABASE_URL: "mysql://timetracker:<password>@db:3306/timetracker"
      #API_KEY_REFRESH_LAST_USED_AFTER: 5s
    ports:
      - 80:80
    links:
      - db
    restart: unless-stopped
    volumes:
      - ./private.pem:/config/private.pem:ro
      - ./public.pem:/config/auth_server.pem:ro

  db:
    environment:
      MYSQL_DATABASE: timetracker
      MYSQL_PASSWORD: <password>
      MYSQL_ROOT_PASSWORD: <password>
      MYSQL_USER: timetracker
    image: mariadb:12.0.2
    restart: unless-stopped
    volumes:
      - ./db_data:/var/lib/mysql
      - ./db_config:/etc/mysql
