//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, serde::Serialize)]
#[sea_orm(table_name = "api_key")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub name: Option<String>,
    #[serde(skip)]
    pub owner: u32,
    pub disabled: bool,
    pub valid_until: Option<DateTimeUtc>,
    pub added: DateTimeUtc,
    pub last_changed: DateTimeUtc,
    pub last_used: Option<DateTimeUtc>,
    #[serde(skip)]
    pub key: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
