//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "job")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    #[serde(skip)]
    pub owner: u32,
    pub name: Option<String>,
    pub company_name: Option<String>,
    pub company_logo: Option<String>,
    pub description: Option<String>,
    pub created: DateTimeUtc,
    pub disabled: bool,
    #[serde(skip)]
    pub active_tracker: Option<u32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tracker::Entity",
        from = "Column::ActiveTracker",
        to = "super::tracker::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Tracker,
}

impl Related<super::tracker::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tracker.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
