//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, serde::Serialize)]
#[sea_orm(table_name = "timeslot")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub tracker: u32,
    pub start: DateTimeUtc,
    pub end: Option<DateTimeUtc>,
    pub comment: Option<String>,
}

impl PartialOrd for Model {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

impl Ord for Model {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        match self.start.cmp(&other.start) {
            std::cmp::Ordering::Equal => self.id.cmp(&other.id),
            ord => ord,
        }
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tracker::Entity",
        from = "Column::Tracker",
        to = "super::tracker::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Tracker,
}

impl Related<super::tracker::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tracker.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
