//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14
use {
    sea_orm::entity::prelude::*,
    serde::{Deserialize, Deserializer, Serialize},
};

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, Default,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "time_pensum_unit")]
#[serde(rename_all = "PascalCase")]
pub enum TimePensumUnit {
    #[sea_orm(string_value = "none")]
    #[default]
    None,
    #[sea_orm(string_value = "week")]
    Week,
    #[sea_orm(string_value = "month")]
    Month,
    #[sea_orm(string_value = "year")]
    Year,
}

impl TimePensumUnit {
    pub fn deserialize_nullable<'de, D: Deserializer<'de>>(
        deserializer: D,
    ) -> Result<Self, D::Error> {
        Ok(Option::deserialize(deserializer)?.unwrap_or_default())
    }
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "display_range_unit")]
#[serde(rename_all = "PascalCase")]
pub enum DisplayRangeUnit {
    #[sea_orm(string_value = "week")]
    Week,
    #[sea_orm(string_value = "month")]
    Month,
    #[sea_orm(string_value = "year")]
    Year,
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "tracker")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub name: Option<String>,
    pub owner: Option<u32>,
    pub job: Option<u32>,
    pub created: DateTimeUtc,
    pub valid_from: Option<DateTimeUtc>,
    pub valid_until: Option<DateTimeUtc>,
    pub time_pensum: Option<u16>,
    pub time_pensum_unit: TimePensumUnit,
    pub display_range_unit: DisplayRangeUnit,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::job::Entity",
        from = "Column::Job",
        to = "super::job::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Job,
    #[sea_orm(has_many = "super::timeslot::Entity")]
    Timeslot,
}

impl Related<super::job::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Job.def()
    }
}

impl Related<super::timeslot::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Timeslot.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
